// This file was autogenerated by ../picnet-closure-repo/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('Utils.js', ['nclosure.external.Utils'], []);
goog.addDependency('Utils.min.js', [], []);
goog.addDependency('deps.js', [], []);
