// This file was autogenerated by ../picnet-closure-repo/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('D:/Dev/nclosure/examples/external_lib/Utils.js', ['nclosure.external.Utils'], []);
goog.addDependency('D:/Dev/nclosure/examples/external_lib/Utils.min.js', [], []);
goog.addDependency('D:/Dev/nclosure/examples/external_lib/deps.js', [], []);
