// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('cat.js', ['nclosure.examples.animals.Cat'], ['nclosure.examples.animals.CatLike', 'nclosure.examples.animals.IAnimal']);
goog.addDependency('catlike.js', ['nclosure.examples.animals.CatLike'], ['nclosure.examples.animals.IAnimal']);
goog.addDependency('deps.js', [], []);
goog.addDependency('docs/javascript/all.js', [], []);
goog.addDependency('docs/javascript/html5.js', [], []);
goog.addDependency('dog.js', ['nclosure.examples.animals.Dog'], ['nclosure.examples.animals.IAnimal']);
goog.addDependency('example.js', ['nclosure.examples.animals.Example'], ['goog.array', 'nclosure.examples.animals.Cat', 'nclosure.examples.animals.Dog', 'nclosure.examples.animals.IAnimal', 'nclosure.examples.animals.Monkey', 'nclosure.examples.animals.Tiger']);
goog.addDependency('ianimal.js', ['nclosure.examples.animals.IAnimal'], []);
goog.addDependency('monkey.js', ['nclosure.examples.animals.Monkey'], ['nclosure.examples.animals.IAnimal']);
goog.addDependency('tiger.js', ['nclosure.examples.animals.Tiger'], ['nclosure.examples.animals.CatLike', 'nclosure.examples.animals.IAnimal']);
