// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../external_lib/Utils.js', ['nclosure.external.Utils'], []);
goog.addDependency('examples/external_lib/deps.js', [], []);
goog.addDependency('examples/simple/deps.js', [], []);
goog.addDependency('examples/simple/docs/javascript/all.js', [], []);
goog.addDependency('examples/simple/docs/javascript/html5.js', [], []);
goog.addDependency('example.js', ['nclosure.examples.simple.Example'], ['goog.async.Delay', 'goog.structs.Trie', 'nclosure.external.Utils']);
goog.addDependency('tests/async/asyncTests.js', ['nclosure.examples.simple.tests.asyncTests'], ['goog.testing.AsyncTestCase', 'goog.testing.jsunit', 'nclosure.examples.simple.Example']);
goog.addDependency('tests/syncTests.js', ['nclosure.examples.simple.tests.syncTests'], ['goog.testing.jsunit', 'nclosure.examples.simple.Example']);
